// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStory struct {
	StoryID  string `json:"storyId"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	UserID   string `json:"userId"`
	UserName string `json:"userName"`
}

type Story struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  *User  `json:"author"`
}

type UpdateStoryInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
